name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "05 3 19 4 *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: xiezipei/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 2a8caa075ad15bc39074ef206e748b59
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
